#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="${SCRIPT_DIR}"
HOME_DIR="$HOME"

link_as_dotfile() {
  local src="${REPO_ROOT}/${1}"
  local dest="${HOME}/.${1}"
  mkdir -p "$(dirname "${dest}")"

  if [ -L "${dest}" ]; then
    rm -f "${dest}"
  elif [ -e "${dest}" ]; then
    mv "${dest}" "${dest}.bak.$(date +%Y%m%d%H%M%S)"
  fi

  ln -s "${src}" "${dest}"
}

if command -v apt-get >/dev/null 2>&1; then
    sudo apt-get install -y \
        btop \
        build-essential \
        ca-certificates \
        containerd.io \
        curl \
        docker-buildx-plugin \
        docker-ce \
        docker-ce-cli \
        docker-compose-plugin \
        eza\
        fzf \
        git \
        git-delta \
        gnupg \
        jq \
        lsb-release \
        ripgrep \
        tmux \
        vim \
        wget 
fi

link_as_dotfile "bashrc"
link_as_dotfile "bin"
link_as_dotfile "gitconfig"
link_as_dotfile "tmux.conf"
link_as_dotfile "vimrc"

if [ "${CODESPACES:-}" = "true" ]; then
  echo "-*- Running inside GitHub Codespaces -*-"
fi
